name: Documentation issue
description: Report a problem with documentation
labels: [ 'area:docs' ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this report!

        If the issue is:

        - A simple typo or similar correction, consider submitting a PR to fix it instead of logging an issue. See our [contributor guide](https://github.com/Tenacom/.github/CONTRIBUTING.md) for instructions.
        - A general support question, consider asking in the Discussions area of the relevant repository.
        - A duplicate of an open or closed issue, leave a comment on that issue.
  - type: input
    attributes:
      label: Affected version(s)
      description: |
        Which is the latest released (not preview) version of the project?

        This will help us keep track of problems more efficiently.
      placeholder: n.n.n
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: Describe the context of the problem. If it affects a specific page, add a link to it.
      placeholder: Remarks section of SomeClass.SomeMethod(int) https://tenacom.github.io/This.Is/Just/AnExample
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problem description
      placeholder: The documentation references a non-existent `GetSomeData` method.
    validations:
      required: true
